services:
  - type: web
    name: typeit74
    runtime: node
    plan: free

    buildCommand: |
      cd client
      npm install
      npm run build
      cd ../server
      npm install

    startCommand: cd server && npm start

    healthCheckPath: /api/health

    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production

      - key: JWT_SECRET
        generateValue: true

      - key: MONGO_URI
        sync: false
